"""Application service contracts and placeholders."""

from agent_os.application.services.agent_invocation_request_factory import (
    WorkspaceAgentInvocationRequestFactory,
)
from agent_os.application.services.agent_runtime_preflight import (
    DEFAULT_AGENT_RUNTIME_TOOLS,
    SUPPORTED_AGENT_RUNTIME_TOOLS,
    AgentRuntimeCandidate,
    AgentRuntimeToolPreflight,
    build_agent_runtime_preflight_report,
    check_agent_runtime_tool,
)
from agent_os.application.services.agent_runtime_profile import (
    AgentRuntimeProfile,
)
from agent_os.application.services.agent_session_discovery import (
    AGENT_SESSION_DISCOVERY_RECORD_SCHEMA,
    AGENT_SESSION_DISCOVERY_SCHEMA,
    AgentSessionDiscoveryRecord,
    discover_agent_sessions,
)
from agent_os.application.services.hermes_registered_session import (
    HermesRegisteredSessionActivationAttempt,
    HermesRegisteredSessionActivationStatus,
    HermesRegisteredSessionHandle,
    HermesRegisteredSessionHandleState,
)
from agent_os.application.services.agent_runtime_permission_read_model import (
    AgentRuntimePermissionView,
    RuntimeAccessGrantView,
    RuntimeDeliveryPlanView,
    RuntimePermissionCapabilityView,
)
from agent_os.application.services.agent_runtime_access import (
    AgentRuntimeAccessGrant,
    AgentRuntimeAccessPlanner,
    AgentRuntimeAccessProfile,
    AgentRuntimeDeliveryDeniedRef,
    AgentRuntimeDeliveryPlan,
    AgentRuntimeDeliverySegmentRef,
    AgentRuntimeKind,
    DelegatedContextDeliveryPolicy,
    RuntimeFilePermission,
    RuntimeMemoryPolicy,
    RuntimeNetworkPolicy,
    RuntimeToolPermission,
)
from agent_os.application.services.agent_exchange import (
    AgentExchangeAttribution,
    AgentExchangeAuthorType,
    AgentExchangeContributionKind,
    AgentExchangeInstructionAuthority,
    AgentExchangeSourceConfidence,
    AgentExchangeSourceType,
    agent_exchange_interface_metadata,
    attach_agent_exchange_metadata,
)
from agent_os.application.services.agent_dispatch import (
    AgentDispatchLeaseRecord,
    AgentDispatchLeaseState,
    AgentDispatchRecord,
    AgentDispatchReplyPolicy,
    AgentDispatchStatus,
)
from agent_os.application.services.agent_endpoint import (
    AgentEndpointContactPolicy,
    AgentEndpointDirection,
    AgentEndpointRecord,
    AgentEndpointState,
    normalize_agent_endpoint_provider,
)
from agent_os.application.services.project_directory_coordination import (
    ProjectDirectoryAccessIntent,
    ProjectDirectoryCommitPolicy,
    ProjectDirectoryCoordinationRecord,
    ProjectDirectoryCoordinationStrength,
    ProjectDirectoryDirtyState,
    ProjectDirectoryOverlapStatus,
    calculate_project_directory_overlap,
    project_directory_coordination_interface_metadata,
)
from agent_os.application.services.context_management_profile import (
    AgentPrivateMemoryConfig,
    ContextAccessAuthorization,
    ContextAccessAuthorizer,
    ContextAccessScope,
    ContextAssemblyError,
    ContextAssemblyPlan,
    ContextAssemblyPlanner,
    ContextAssemblyRequest,
    ContextContentKind,
    ContextContentPacketBuilder,
    ContextContentPacketDeliveryMode,
    ContextContentPacketItem,
    ContextContentPacketPlan,
    ContextContentState,
    ContextConversationMessageSnapshot,
    ContextExcludedContentRef,
    ContextLocalContentMaterializer,
    ContextDeniedScope,
    ContextManagementProfile,
    ContextManagementProfileResolver,
    ContextManagementStrategy,
    ContextMaterializationLoadState,
    ContextMaterializationPlan,
    ContextMaterializedSegment,
    ContextMaterializedSegmentKind,
    ContextOverflowMode,
    ContextOmittedSourceRef,
    ExternalContextEngineConfig,
    ContextSourceRef,
    ContextSharedContextUpdateSnapshot,
    ContextTaskContextSnapshot,
    ContextWindowSelectionPlan,
    ContextWindowSelectionPolicy,
    ContextWindowSelector,
    ProviderNativeContextConfig,
)
from agent_os.application.services.file_operation_context_linker import (
    FileOperationContextLinker,
)
from agent_os.application.services.file_operation_service import (
    FileOperationAuditRecorderPort,
    FileOperationService,
    RecordedFileOperationResult,
    audit_safe_file_operation_result,
)
from agent_os.application.services.file_operation_request_factory import (
    WorkspaceFileOperationPolicy,
    WorkspaceFileOperationRequestFactory,
)
from agent_os.application.services.local_single_turn_platform_use_case import (
    LocalSingleTurnPlatformUseCase,
)
from agent_os.application.services.local_platform_operations import (
    LocalPlatformOperationService,
)
from agent_os.application.services.local_platform_application import (
    LocalPlatformApplication,
)
from agent_os.application.services.model_provider_selection import (
    ModelProviderSelection,
    build_provider_backed_agent_invocation_adapter,
)
from agent_os.application.services.platform_invocation_gateway_handler import (
    PLATFORM_SINGLE_TURN_INVOCATION_KIND,
    PLATFORM_SINGLE_TURN_INVOCATION_NOT_WIRED_KIND,
    PlatformInvocationGatewayHandler,
)
from agent_os.application.services.platform_invocation_gateway_entrypoint import (
    PlatformInvocationGatewayEnvelopeAdapter,
    handle_platform_invocation_gateway_envelope,
)
from agent_os.application.services.platform_invocation_gateway_bridge import (
    PLATFORM_SINGLE_TURN_INVOCATION_COMPLETED_KIND,
    SqlitePlatformInvocationGatewayRuntimeBridge,
)
from agent_os.application.services.platform_invocation_gateway_transport import (
    PlatformInvocationGatewayTransportAdapter,
)
from agent_os.application.services.platform_invocation_local_entrypoint import (
    LocalPlatformInvocationEntrypoint,
    handle_local_platform_invocation_payload,
)
from agent_os.application.services.platform_invocation_runtime_handler import (
    PLATFORM_INVOCATION_RESPONSE_FIELDS,
    PLATFORM_INVOCATION_RESULT_FIELDS,
    PLATFORM_INVOCATION_USER_CONTEXT_UPDATE_FIELDS,
    SqlitePlatformInvocationRuntimeHandler,
    handle_sqlite_platform_invocation_payload,
)
from agent_os.application.services.provider_backed_agent_invocation_adapter import (
    ProviderBackedAgentInvocationAdapter,
)
from agent_os.application.services.single_turn_platform_runtime import (
    AgentInvocationAdapterPort,
    AgentInvocationRecorderPort,
    ContextUpdateRecorderPort,
    DeterministicAgentInvocationAdapter,
    RecordedContextUpdateView,
    SingleTurnPlatformRunResult,
    SingleTurnPlatformRuntime,
)
from agent_os.application.services.workspace_file_operation_use_case import (
    WorkspaceFileOperationUseCase,
)

__all__ = (
    "FileOperationContextLinker",
    "AgentRuntimeProfile",
    "AGENT_SESSION_DISCOVERY_RECORD_SCHEMA",
    "AGENT_SESSION_DISCOVERY_SCHEMA",
    "AgentSessionDiscoveryRecord",
    "HermesRegisteredSessionActivationAttempt",
    "HermesRegisteredSessionActivationStatus",
    "HermesRegisteredSessionHandle",
    "HermesRegisteredSessionHandleState",
    "DEFAULT_AGENT_RUNTIME_TOOLS",
    "SUPPORTED_AGENT_RUNTIME_TOOLS",
    "AgentRuntimeCandidate",
    "AgentRuntimeToolPreflight",
    "build_agent_runtime_preflight_report",
    "check_agent_runtime_tool",
    "AgentRuntimePermissionView",
    "AgentRuntimeAccessGrant",
    "AgentRuntimeAccessPlanner",
    "AgentRuntimeAccessProfile",
    "AgentRuntimeDeliveryDeniedRef",
    "AgentRuntimeDeliveryPlan",
    "AgentRuntimeDeliverySegmentRef",
    "AgentRuntimeKind",
    "RuntimeAccessGrantView",
    "RuntimeDeliveryPlanView",
    "RuntimePermissionCapabilityView",
    "AgentExchangeAttribution",
    "AgentExchangeAuthorType",
    "AgentExchangeContributionKind",
    "AgentExchangeInstructionAuthority",
    "AgentExchangeSourceConfidence",
    "AgentExchangeSourceType",
    "AgentDispatchLeaseRecord",
    "AgentDispatchLeaseState",
    "AgentDispatchRecord",
    "AgentDispatchReplyPolicy",
    "AgentDispatchStatus",
    "AgentEndpointContactPolicy",
    "AgentEndpointDirection",
    "AgentEndpointRecord",
    "AgentEndpointState",
    "normalize_agent_endpoint_provider",
    "ProjectDirectoryAccessIntent",
    "ProjectDirectoryCommitPolicy",
    "ProjectDirectoryCoordinationRecord",
    "ProjectDirectoryCoordinationStrength",
    "ProjectDirectoryDirtyState",
    "ProjectDirectoryOverlapStatus",
    "AgentPrivateMemoryConfig",
    "ContextAccessAuthorization",
    "ContextAccessAuthorizer",
    "ContextAccessScope",
    "ContextAssemblyError",
    "ContextAssemblyPlan",
    "ContextAssemblyPlanner",
    "ContextAssemblyRequest",
    "ContextContentKind",
    "ContextContentPacketBuilder",
    "ContextContentPacketDeliveryMode",
    "ContextContentPacketItem",
    "ContextContentPacketPlan",
    "ContextContentState",
    "ContextConversationMessageSnapshot",
    "ContextExcludedContentRef",
    "ContextLocalContentMaterializer",
    "ContextDeniedScope",
    "ContextManagementProfile",
    "ContextManagementProfileResolver",
    "ContextManagementStrategy",
    "ContextMaterializationLoadState",
    "ContextMaterializationPlan",
    "ContextMaterializedSegment",
    "ContextMaterializedSegmentKind",
    "ContextOverflowMode",
    "ContextOmittedSourceRef",
    "ExternalContextEngineConfig",
    "ContextSourceRef",
    "ContextSharedContextUpdateSnapshot",
    "ContextTaskContextSnapshot",
    "ContextWindowSelectionPlan",
    "ContextWindowSelectionPolicy",
    "ContextWindowSelector",
    "DelegatedContextDeliveryPolicy",
    "ProviderNativeContextConfig",
    "WorkspaceAgentInvocationRequestFactory",
    "FileOperationAuditRecorderPort",
    "FileOperationService",
    "LocalSingleTurnPlatformUseCase",
    "LocalPlatformOperationService",
    "LocalPlatformApplication",
    "ModelProviderSelection",
    "PLATFORM_SINGLE_TURN_INVOCATION_KIND",
    "PLATFORM_SINGLE_TURN_INVOCATION_COMPLETED_KIND",
    "PLATFORM_SINGLE_TURN_INVOCATION_NOT_WIRED_KIND",
    "PLATFORM_INVOCATION_RESPONSE_FIELDS",
    "PLATFORM_INVOCATION_RESULT_FIELDS",
    "PLATFORM_INVOCATION_USER_CONTEXT_UPDATE_FIELDS",
    "PlatformInvocationGatewayEnvelopeAdapter",
    "PlatformInvocationGatewayHandler",
    "PlatformInvocationGatewayTransportAdapter",
    "ProviderBackedAgentInvocationAdapter",
    "RuntimeFilePermission",
    "RuntimeMemoryPolicy",
    "RuntimeNetworkPolicy",
    "RuntimeToolPermission",
    "LocalPlatformInvocationEntrypoint",
    "SqlitePlatformInvocationGatewayRuntimeBridge",
    "SqlitePlatformInvocationRuntimeHandler",
    "handle_platform_invocation_gateway_envelope",
    "handle_local_platform_invocation_payload",
    "handle_sqlite_platform_invocation_payload",
    "AgentInvocationAdapterPort",
    "AgentInvocationRecorderPort",
    "ContextUpdateRecorderPort",
    "DeterministicAgentInvocationAdapter",
    "RecordedFileOperationResult",
    "RecordedContextUpdateView",
    "SingleTurnPlatformRunResult",
    "SingleTurnPlatformRuntime",
    "audit_safe_file_operation_result",
    "agent_exchange_interface_metadata",
    "attach_agent_exchange_metadata",
    "calculate_project_directory_overlap",
    "project_directory_coordination_interface_metadata",
    "build_provider_backed_agent_invocation_adapter",
    "discover_agent_sessions",
    "WorkspaceFileOperationPolicy",
    "WorkspaceFileOperationRequestFactory",
    "WorkspaceFileOperationUseCase",
)
